namespace MiniTwitch.Helix.Internal.Enums;

[Flags]
internal enum Scopes : ulong
{
    None,
    Analytics_Read_Extensions = 1UL << 1,
    Analytics_Read_Games = 1UL << 2,
    Bits_Read = 1UL << 3,
    Channel_Manage_Broadcast = 1UL << 4,
    Channel_Read_Charity = 1UL << 5,
    Channel_Edit_Commercial = 1UL << 6,
    Channel_Read_Editors = 1UL << 7,
    Channel_Manage_Extensions = 1UL << 8,
    Channel_Read_Goals = 1UL << 9,
    Channel_Read_Guest_Star = 1UL << 10,
    Channel_Manage_Guest_Star = 1UL << 11,
    Channel_Read_Hype_Train = 1UL << 12,
    Channel_Manage_Moderators = 1UL << 13,
    Channel_Read_Polls = 1UL << 14,
    Channel_Manage_Polls = 1UL << 15,
    Channel_Read_Predictions = 1UL << 16,
    Channel_Manage_Predictions = 1UL << 17,
    Channel_Manage_Raids = 1UL << 18,
    Channel_Read_Redemptions = 1UL << 19,
    Channel_Manage_Redemptions = 1UL << 20,
    Channel_Manage_Schedule = 1UL << 21,
    Channel_Read_Stream_Key = 1UL << 22,
    Channel_Read_Subscriptions = 1UL << 23,
    Channel_Manage_Videos = 1UL << 24,
    Channel_Read_Vips = 1UL << 25,
    Channel_Manage_Vips = 1UL << 26,
    Clips_Edit = 1UL << 27,
    Moderation_Read = 1UL << 28,
    Moderator_Manage_Announcements = 1UL << 29,
    Moderator_Manage_Automod = 1UL << 30,
    Moderator_Read_Automod_settings = 1UL << 31,
    Moderator_Manage_Automod_settings = 1UL << 32,
    Moderator_Manage_Banned_Users = 1UL << 33,
    Moderator_Read_Blocked_Terms = 1UL << 34,
    Moderator_Manage_Blocked_Terms = 1UL << 35,
    Moderator_Manage_Chat_Messages = 1UL << 36,
    Moderator_Read_Chat_Settings = 1UL << 37,
    Moderator_Manage_Chat_Settings = 1UL << 38,
    Moderator_Read_Chatters = 1UL << 39,
    Moderator_Read_Followers = 1UL << 40,
    Moderator_Read_Guest_Star = 1UL << 41,
    Moderator_Manage_Guest_Star = 1UL << 42,
    Moderator_Read_Shield_Mode = 1UL << 43,
    Moderator_Manage_Shield_Mode = 1UL << 44,
    Moderator_Read_Shoutouts = 1UL << 45,
    Moderator_Manage_Shoutouts = 1UL << 46,
    User_Edit = 1UL << 47,
    User_Edit_Follows = 1UL << 48,
    User_Read_Blocked_Users = 1UL << 49,
    User_Manage_Blocked_Users = 1UL << 50,
    User_Read_Broadcast = 1UL << 51,
    User_Manage_Chat_Color = 1UL << 52,
    User_Read_Email = 1UL << 53,
    User_Read_Follows = 1UL << 54,
    User_Read_Subscriptions = 1UL << 55,
    User_Manage_Whispers = 1UL << 56,
    User_Edit_Broadcast = 1UL << 57
}
